"use strict";
exports.__esModule = true;
var Cliente_1 = require("./Clases/Cliente");
var libro_1 = require("./Clases/libro");
var Revista_1 = require("./Clases/Revista");
var Libreria_1 = require("./Clases/Libreria");
var listaDeEscritores = ['J.K Rowling', 'Stephen King', 'Gabriel Garcia Marquez'];
var listaDeGeneros = ['Ciencia ficion', 'Terror', 'Realismo magico'];
var libroUno = new libro_1.Libro('Terror', 852, 'No tiene un resumen', 'Cuento de hadas', 'Stephen King', 9800);
var libroDos = new libro_1.Libro('Dramatico', 208, 'Aca va el resumen', 'Hamlet', 'Willam Shakespeare', 2300);
var libroTres = new libro_1.Libro('No ficcion', 379, 'No tiene un resumen', 'Las venas abiertas de america latina', 'Eduardo Galeano', 4790);
var revistaUno = new Revista_1.Revista(2022, 90, 'America latina hoy', 'Hernan campos parra y Patricio Daniel Navia', 390);
var revistaDos = new Revista_1.Revista(2022, 70, 'Cocinando en casa', 'pepe garcia y soledad lala', 290);
var revistaTres = new Revista_1.Revista(2022, 81, 'art attack', 'pedro alfonso', 250);
var clienteUno = new Cliente_1.Cliente(listaDeEscritores, listaDeGeneros, 30, 'Juan', 'Garcia', 17369421, 'Av siempre viva 114');
var clienteDos = new Cliente_1.Cliente(listaDeEscritores, listaDeGeneros, 15, 'Jorge', 'Marquez', 26451351, 'San Matrin 852');
var clienteTres = new Cliente_1.Cliente(listaDeEscritores, listaDeGeneros, 10, 'Laura', 'Romano', 31258521, 'Isla de los estados 612');
var listaClientes = [clienteUno, clienteDos, clienteTres];
var listaLibros = [libroUno, libroDos, libroTres];
var listaRevistas = [revistaUno, revistaDos, revistaTres];
var libreria = new Libreria_1.Libreria(listaLibros, listaRevistas, listaClientes);
console.log(' El precio del libro de: ' + libroTres.getNombre() + ' es de: ' + '$' + libroTres.getPrecio() + ' Suscrito -Lectores abanzados- 30%  ' + '$' + libreria.descuento(clienteUno, libroTres) + ' para el cliente ' + clienteUno.getNombre() + ' ' + clienteUno.getApellido());
console.log(' El precio de la revista de ' + revistaUno.getNombre() + ' es de: ' + '$' + revistaUno.getPrecio() + ' suscrito -Lectores Media- 15% ' + '$' + libreria.descuento(clienteDos, revistaUno) + ' para el cliente ' + clienteDos.getNombre() + ' ' + clienteDos.getApellido());
